# fly.toml app configuration file generated for portfolio-els-server on 2023-08-09T19:57:44+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "portfolio-els-server"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
